version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
    #app1 listens on port 3000 inside the container, but it's mapped to port 3001 on local machine
      - "3001:3000"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"
